[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas-price = 10000000000000





solc_version = "0.8.20"  
[etherscan]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
core = "${CORE_TESTNET_RPC_URL}"
core_explorer="${CORE_EXPLORER}"
